name: Terraform S3 Module Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test S3 Bucket Module
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.5.7'
        
    - name: Install Terragrunt
      run: |
        TERRAGRUNT_VERSION=v0.53.2
        wget -q https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 -O /tmp/terragrunt
        chmod +x /tmp/terragrunt
        sudo mv /tmp/terragrunt /usr/local/bin/terragrunt
        terragrunt --version
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Validate Terraform Module
      run: |
        cd terraform/modules/s3-bucket
        terraform init -backend=false
        terraform validate
        
    - name: Install Go dependencies
      run: |
        cd test
        go mod init github.com/nhaila-abdessamad/terraform-s3-bucket-test
        go get github.com/gruntwork-io/terratest@v0.46.0
        go get github.com/gruntwork-io/terratest/modules/terraform@v0.46.0
        go get github.com/gruntwork-io/terratest/modules/random@v0.46.0
        go get github.com/stretchr/testify/assert@v1.8.4
        go get github.com/aws/aws-sdk-go@v1.45.15
        go mod tidy
        
    - name: Run Terratest
      run: |
        cd test
        export AWS_REGION=us-east-1
        export TG_VAR_environment=testenv
        export AWS_SDK_LOAD_CONFIG=1
        go test -v -timeout 30m ./...