name: Terragrunt and Terratest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Terragrunt Configuration
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.5.7'
        
    - name: Install Terragrunt
      run: |
        TERRAGRUNT_VERSION=v0.53.2
        wget -q https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 -O /tmp/terragrunt
        chmod +x /tmp/terragrunt
        sudo mv /tmp/terragrunt /usr/local/bin/terragrunt
        terragrunt --version
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    # Setup project structure to match expectations in the test
    - name: Setup proper directory structure
      run: |
        # Create the necessary directory structure
        mkdir -p terraform/modules/s3-bucket
        mkdir -p terragrunt/environments/dev/s3-bucket
        mkdir -p terragrunt/environments/dev/log-bucket
        
        # Copy files to the proper locations
        cp main.tf terraform/modules/s3-bucket/
        cp variables.tf terraform/modules/s3-bucket/
        cp outputs.tf terraform/modules/s3-bucket/
        
        # Setup terragrunt files
        cp terragrunt.hcl terragrunt/environments/dev/s3-bucket/
        cp terraform.tfvars terragrunt/environments/dev/s3-bucket/
        
        # Create the parent terragrunt.hcl file
        cat > terragrunt/terragrunt.hcl << EOF
        # This is the parent terragrunt configuration
        remote_state {
          backend = "local"
          config = {
            path = "\${path_relative_to_include()}/terraform.tfstate"
          }
        }
        EOF
        
        # Copy to root of terragrunt directory
        cp terragrunt/terragrunt.hcl terragrunt/environments/dev/
        
        # Create basic log bucket configuration
        cat > terragrunt/environments/dev/log-bucket/terragrunt.hcl << EOF
        include {
          path = find_in_parent_folders()
        }
        
        # This is just a mock module to satisfy dependency
        # It will not actually be applied in testing
        EOF
        
    - name: Validate Terraform module
      run: |
        cd terraform/modules/s3-bucket
        terraform init -backend=false
        terraform validate
        
    - name: Install Go dependencies
      run: |
        cd test
        go mod init github.com/yourusername/terraform-s3-bucket-test
        go get github.com/gruntwork-io/terratest@v0.46.0
        go get github.com/gruntwork-io/terratest/modules/terraform@v0.46.0
        go get github.com/gruntwork-io/terratest/modules/random@v0.46.0
        go get github.com/stretchr/testify/assert@v1.8.4
        go get github.com/stretchr/testify/require@v1.8.4
        go get github.com/aws/aws-sdk-go@v1.45.15
        go mod tidy
        
    - name: Run Terratest
      run: |
        cd test
        # Set environment variables to control terragrunt behavior
        export AWS_REGION=us-east-1
        export TG_VAR_environment=testenv
        export AWS_SDK_LOAD_CONFIG=1
        go test -v -timeout 30m ./...